version: '3.1'

services :
  db:
    image: postgres
    networks:
      - net
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: kirill
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: postgres

  admin:
    image: adminer
    depends_on:
      - db
    ports:
      - '9999:8080'

  backend:
    build: .
    image: mobile-avengers/backend:latest
    depends_on:
      - db
    networks:
      - net
    ports:
      - '8080:8080'

networks:
  net:
    driver: bridge
